title:        OWTF
tagline:      'Offensive Web Testing Framework'
description:  'OWASP OWTF, the Offensive (Web) Testing Framework, is an OWASP+PTES-focused try to unite great tools and make pen testing more efficient, written mostly in Python'
version:      1.0.1 "LionHeart"
author:
  name:       'Abraham Aranguren'
  email:      'name.surname@owasp.org'
markdown:     kramdown
highlighter:    true
future:      true
baseurl:  http://owtf.github.io/boilerplate-templates
